--- 
abstract: alias C<__::__> to C<__PACKAGE__>
author: 
  - "C<mst> on C<#moose>:"
build_requires: 
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: __
no_index: 
  directory: 
    - inc
    - t
version: 0.01
